[templates.firefox-websites]
input_path = '~/.config/matugen/templates/firefox-websites.css'
output_path = '~/.config/matugen/generated/firefox-websites.css'
post_hook = '''
bash -c '
{
  if command -v firefox >/dev/null 2>&1; then
    ln -nfs "$HOME/.config/matugen/generated/firefox-websites.css" "$HOME/.config/mozilla/firefox/n600oyoy.default-release-1771562099779/chrome/colors.css"
  fi
} >/dev/null 2>&1 </dev/null & disown
'
'''

# NOTE: THIS IS AN EXAMPLE ***ONLY***
# MUST BE CONFIGURED TO WORK WITH USER'S FIREFOX PROFILE DIRECTORY